name: hom_mobile
description: HOM — Hospitality Operations Manager
publish_to: 'none'
version: 2.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  url_launcher: ^6.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  msix: ^3.16.8
flutter:
  uses-material-design: true
  assets:
    - assets/logo/

msix_config:
  display_name: HOM
  publisher_display_name: Hexadigitall
  identity_name: com.hexadigitall.hom
  publisher: CN=Hexadigitall, O=Hexadigitall, C=NG
  logo_path: windows/runner/resources/app_icon.png
  capabilities: internetClient
  languages: en-us
  msix_version: 2.0.0.0
