// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIQYzEzDQEOcRSV_PriNCtPNjLOuOv4ps',
    appId: '1:925042136693:web:d790372a5338b4a6e64a3c',
    messagingSenderId: '925042136693',
    projectId: 'hom-os',
    authDomain: 'hom-os.firebaseapp.com',
    storageBucket: 'hom-os.firebasestorage.app',
    measurementId: 'G-0YVWRT9TZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1br7GJbBwNqzNzTUdLbCvts2aZ6gdwmc',
    appId: '1:925042136693:android:bfa4302cd8090aafe64a3c',
    messagingSenderId: '925042136693',
    projectId: 'hom-os',
    storageBucket: 'hom-os.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-6z5ZRL3TUXzUiK0ibFoaTqrZJj27BgM',
    appId: '1:925042136693:ios:06b1769628dc54d8e64a3c',
    messagingSenderId: '925042136693',
    projectId: 'hom-os',
    storageBucket: 'hom-os.firebasestorage.app',
    androidClientId: '925042136693-so1ki1f497aldnhhgrkkjfi8tj9r6kd5.apps.googleusercontent.com',
    iosClientId: '925042136693-kv2hplorbv20m1rj9vau1g176ak5cssl.apps.googleusercontent.com',
    iosBundleId: 'com.hom.homMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-6z5ZRL3TUXzUiK0ibFoaTqrZJj27BgM',
    appId: '1:925042136693:ios:06b1769628dc54d8e64a3c',
    messagingSenderId: '925042136693',
    projectId: 'hom-os',
    storageBucket: 'hom-os.firebasestorage.app',
    androidClientId: '925042136693-so1ki1f497aldnhhgrkkjfi8tj9r6kd5.apps.googleusercontent.com',
    iosClientId: '925042136693-kv2hplorbv20m1rj9vau1g176ak5cssl.apps.googleusercontent.com',
    iosBundleId: 'com.hom.homMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIQYzEzDQEOcRSV_PriNCtPNjLOuOv4ps',
    appId: '1:925042136693:web:6a636888400e6a3ce64a3c',
    messagingSenderId: '925042136693',
    projectId: 'hom-os',
    authDomain: 'hom-os.firebaseapp.com',
    storageBucket: 'hom-os.firebasestorage.app',
    measurementId: 'G-VES5KLW4KM',
  );
}
